version: '3.8'

services:
  # Node.js Backend
  node_eccomweb:
    build: ./Eccomerce-MeanStack-And-TSNode  # If your Dockerfile is in the sub-directory
    container_name: node_eccombackend
    ports:
      - "3000:4000"  # Mapping port 3000 on host to 3000 on container
    env_file:
      - ./Eccomerce-MeanStack-And-TSNode/.env  # Make sure this file exists and is correct
    depends_on:
      - postgres_db  # Ensures that Postgres starts before the node app
    volumes:
      - uploads_data:/app/uploads # Correctly mapping volume to path
    networks:
      - ecommerce_network

  # PostgreSQL Database
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"  # Mapping PostgreSQL port
    networks:
      - ecommerce_network

volumes:
  uploads_data:


networks:
  ecommerce_network:
    driver: bridge
